center_weight: 2.0
center:
  _target_: GaussianLSS.losses.CenterLoss

  min_visibility: ${min_visibility}
  key: vehicle

offset_weight:  0.1
offset:
  _target_: GaussianLSS.losses.OffsetLoss

  min_visibility: ${min_visibility}
  key: vehicle

vehicle_weight: 1.0
vehicle:
  _target_: GaussianLSS.losses.BinarySegmentationLoss

  key: vehicle
  min_visibility: ${min_visibility}
